---
slime_drop:
  metadata:
    tag: slime_drop
    type: MISC
    slimeDropValue: 1
    duration: 0

fireball:
  metadata:
    tag: fireball
    type: SPELL
    slimeDropValue: 250
    duration: 0

heal_potion:
  metadata:
    tag: heal_potion
    type: CONSUMABLE
    slimeDropValue: 100
    duration: 0

  Stats:
    baseStats:
      hp: 25.0

    observableStats: {}

mana_potion:
  metadata:
    tag: mana_potion
    type: CONSUMABLE
    slimeDropValue: 10
    duration: 0

  Stats:
    baseStats:
      mp: 25.0

    observableStats: {}

speed_potion:
  metadata:
    tag: speed_potion
    type: CONSUMABLE
    slimeDropValue: 10
    duration: 5000

  Stats:
    baseStats:
      spd: 2.0

    observableStats: {}